### ISSUE TITLE
NullPointerException if no filter in SLD layer

### ISSUE THREAD

**Issue by SGroe** [emplexed/gs-mvt#6]
A NullPointerException occurs if there is no filter for a layer in the SLD style.

Adding a dummy filter solves the problem. However, it would be better if the plugin can handle layers without a SLD filter.

java.lang.NullPointerException
    at org.geotools.filter.visitor.SimplifyingFilterVisitor.collect(SimplifyingFilterVisitor.java:234)
    at org.geotools.filter.visitor.SimplifyingFilterVisitor.visit(SimplifyingFilterVisitor.java:292)
    at org.geotools.filter.OrImpl.accept(OrImpl.java:49)
    at org.geotools.filter.visitor.SimplifyingFilterVisitor.collect(SimplifyingFilterVisitor.java:234)
    at org.geotools.filter.visitor.SimplifyingFilterVisitor.visit(SimplifyingFilterVisitor.java:164)
    at org.geotools.filter.AndImpl.accept(AndImpl.java:52)
    at org.geotools.filter.visitor.SimplifyingFilterVisitor.simplify(SimplifyingFilterVisitor.java:524)
    at org.geotools.filter.visitor.SimplifyingFilterVisitor.simplify(SimplifyingFilterVisitor.java:508)
    at org.geotools.data.DataUtilities.mixQueries(DataUtilities.java:2502)
    at org.geoserver.wms.mvt.StreamingMVTMap.encode(StreamingMVTMap.java:80)

**Comment by stefan0722** [comment]
A null guard has been added. This issue has been fixed in Version 0.3.0
